# Generated by Django 3.0.6 on 2020-05-05 15:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Логин')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка для парсинга')),
                ('pages', models.PositiveIntegerField(default=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.User')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, db_index=True, verbose_name='Описание')),
                ('name_seller', models.CharField(max_length=100, verbose_name='Имя продавца')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер продавца')),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField(verbose_name='Ссылка на объявление')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Search')),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
